export const FETCH_CAMPAING = 'FETCH_CAMPAING';
export const FETCH_CAMPAING_OK = 'FETCH_CAMPAING_OK';
export const FETCH_CAMPAING_KO = 'FETCH_CAMPAING_KO';

export const GET_CAMPAING = 'GET_CAMPAING';
export const GET_CAMPAING_OK = 'GET_CAMPAING_OK';
export const GET_CAMPAING_KO = 'GET_CAMPAING_KO';