export const FETCH_CAMPAING = 'FETCH_CAMPAING';
export const FETCH_CAMPAING_OK = 'FETCH_CAMPAING_OK';
export const FETCH_CAMPAING_KO = 'FETCH_CAMPAING_KO';

export const FETCH_CAMPAINGSMS = 'FETCH_CAMPAINGSMS';
export const FETCH_CAMPAINGSMS_OK = 'FETCH_CAMPAINGSMS_OK';
export const FETCH_CAMPAINGSMS_KO = 'FETCH_CAMPAINGSMS_KO';

export const GET_CAMPAING = 'GET_CAMPAING';
export const GET_CAMPAING_OK = 'GET_CAMPAING_OK';
export const GET_CAMPAING_KO = 'GET_CAMPAING_KO';

export const GET_CAMPAINGSMS = 'GET_CAMPAINGSMS';
export const GET_CAMPAINGSMS_OK = 'GET_CAMPAINGSMS_OK';
export const GET_CAMPAINGSMS_KO = 'GET_CAMPAINGSMS_KO';

export const GET_CAMPAINGSMSFILE = 'GET_CAMPAINGSMSFILE';
export const GET_CAMPAINGSMSFILE_OK = 'GET_CAMPAINGSMSFILE_OK';
export const GET_CAMPAINGSMSFILE_KO = 'GET_CAMPAINGSMSFILE_KO';

export const GET_CAMPAINGFILE = 'GET_CAMPAINGFILE';
export const GET_CAMPAINGFILE_OK = 'GET_CAMPAINGFILE_OK';
export const GET_CAMPAINGFILE_KO = 'GET_CAMPAINGFILE_KO';