export const FETCH_COMPANY = 'FETCH_COMPANY';
export const FETCH_COMPANY_OK = 'FETCH_COMPANY_OK';
export const FETCH_COMPANY_KO = 'FETCH_COMPANY_KO';

export const POST_COMPANY = 'POST_COMPANY';
export const POST_COMPANY_OK = 'POST_COMPANY_OK';
export const POST_COMPANY_KO = 'POST_COMPANY_KO';

export const DELETE_COMPANY = 'DELETE_COMPANY';
export const DELETE_COMPANY_OK = 'DELETE_COMPANY_OK';
export const DELETE_COMPANY_KO = 'DELETE_COMPANY_KO';

export const PATCH_COMPANY = 'PATCH_COMPANY';
export const PATCH_COMPANY_OK = 'PATCH_COMPANY_OK';
export const PATCH_COMPANY_KO = 'PATCH_COMPANY_KO';