export const GET_DEP_MUNI = 'GET_DEP_MUNI';
export const GET_DEP_MUNI_OK = 'GET_DEP_MUNI_OK';
export const GET_DEP_MUNI_KO = 'GET_DEP_MUNI_KO';

export const GET_FILTER = 'GET_FILTER';
export const GET_FILTER_OK = 'GET_FILTER_OK';
export const GET_FILTER_KO = 'GET_FILTER_KO';

export const FILTER_DATA = 'FILTER_DATA';
export const FILTER_DATA_OK = 'FILTER_DATA_OK';
export const FILTER_DATA_KO = 'FILTER_DATA_KO';


export const CREATEDGROUP = 'CREATEDGROUP';
export const CREATEDGROUP_OK = 'CREATEDGROUP_OK';
export const CREATEDGROUP_KO = 'CREATEDGROUP_KO';

export const GETGROUP = 'GETGROUP';
export const GETGROUP_OK = 'GETGROUP_OK';
export const GETGROUP_KO = 'GETGROUP_KO';

export const CHANGE_FLAG = 'CHANGE_FLAG';
export const CHANGE_FLAG_OK = 'CHANGE_FLAG_OK';
export const CHANGE_FLAG_KO = 'CHANGE_FLAG_KO';

export const GET_INFO = 'GET_INFO';
export const GET_INFO_OK = 'GET_INFO_OK';
export const GET_INFO_KO = 'GET_INFO_KO';

export const DOWNLOADFILTER_DATA = 'DOWNLOADFILTER_DATA';
export const DOWNLOADFILTER_DATA_OK = 'DOWNLOADFILTER_DATA_OK';
export const DOWNLOADFILTER_DATA_KO = 'DOWNLOADFILTER_DATA_KO';