export const POST_REGISTER = 'POST_REGISTER';
export const POST_REGISTER_OK = 'POST_REGISTER_OK';
export const POST_REGISTER_KO = 'POST_REGISTER_KO';

export const POST_SIGNIN = 'POST_SIGNIN';
export const POST_SIGNIN_OK = 'POST_SIGNIN_OK';
export const POST_SIGNIN_KO = 'POST_SIGNIN_KO';

export const POST_FORGOT_PASS = 'POST_FORGOT_PASS';
export const POST_FORGOT_PASS_OK = 'POST_FORGOT_PASS_OK';
export const POST_FORGOT_PASS_KO = 'POST_FORGOT_PASS_KO';

export const POST_RESET_PASS = 'POST_RESET_PASS';
export const POST_RESET_PASS_OK = 'POST_RESET_PASS_OK';
export const POST_RESET_PASS_KO = 'POST_RESET_PASS_KO';

export const POST_CONFIRM_TOKEN = 'POST_CONFIRM_TOKEN';
export const POST_CONFIRM_TOKEN_OK = 'POST_CONFIRM_TOKEN_OK';
export const POST_CONFIRM_TOKEN_KO = 'POST_CONFIRM_TOKEN_KO';

export const POST_SIGNOUT = 'POST_SIGNOUT';
export const POST_SIGNOUT_OK = 'POST_SIGNOUT_OK';
export const POST_SIGNOUT_KO = 'POST_SIGNOUT_KO';
